// Re-export types from @armory-sh/base
export type {
  PaymentPayloadV1,
  PaymentRequirementsV1,
  SettlementResponseV1,
  PaymentPayloadV2,
  PaymentRequirementsV2,
  SettlementResponseV2,
  PaymentPayload,
  PaymentRequirements,
  SettlementResponse,
  CAIP2ChainId,
  CAIPAssetId,
  Address,
  Signature,
  PayToV2,
  Extensions,
  NetworkConfig,
  TransferWithAuthorizationParams,
  BalanceOfParams,
} from "@armory-sh/base";

export {
  V1_HEADERS,
  V2_HEADERS,
  isV1,
  isV2,
  getPaymentVersion,
  getRequirementsVersion,
  getSettlementVersion,
  getPaymentHeaderName,
  getPaymentResponseHeaderName,
  getPaymentRequiredHeaderName,
  isSettlementSuccessful,
  getTxHash,
  NETWORKS,
  getNetworkConfig,
  getNetworkByChainId,
  getMainnets,
  getTestnets,
  ERC20_ABI,
  encodePaymentV1,
  decodePaymentV1,
  encodeSettlementV1,
  decodeSettlementV1,
  encodePaymentV2,
  decodePaymentV2,
  encodeSettlementV2,
  decodeSettlementV2,
  detectPaymentVersion,
  decodePayment,
  decodeSettlementLegacy,
  isPaymentV1,
  isPaymentV2,
  isSettlementV1,
  isSettlementV2,
  EIP712_TYPES,
  createEIP712Domain,
  createTransferWithAuthorization,
  validateTransferWithAuthorization,
  isCAIP2ChainId,
  isCAIPAssetId,
  isAddress,
} from "@armory-sh/base";

// Ethers-specific exports
export {
  createPaymentPayloadV1,
  createPaymentPayloadV2,
  createPaymentPayload,
  parsePaymentRequirements,
  detectProtocolVersion,
} from "./protocol";

export type { Signer } from "./types";
export type { X402ClientConfig, ClientConfig } from "./types";
export { createX402Transport } from "./transport";
